openapi: 3.1.0
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'https'
paths:
  /api/place:
    get:
      summary: Get all places
      responses:
        200:
          description: Place details
        404:
          description: Place not found
  /api/place?id={id}:
    get:
      summary: Get a place by ID
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Place details
        404:
          description: Place not found
